[build]
  command="npm run build"
  functions="functions"
  publish="build"

[[redirects]]
  to="/.netlify/functions/api/:splat"
  from="/api/*"
  status=200

[[redirects]]
  from="/*"
  to="/index.html"
  status=200

[[headers]]
  for="/*"
  [headers.values]
    X-Content-Type-Options="nosniff"