/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE'
export const LOAD_USER = 'LOAD_USER'

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_USER_NOT_EXIST = 'LOGIN_USER_NOT_EXIST'
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_EXIST = 'REGISTER_USER_EXIST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'
export const PASSWORD_COPY_TO_CLIPBOARD = 'PASSWORD_COPY_TO_CLIPBOARD'
export const LOGOUT_USER = 'LOGOUT_USER'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RESET_PASSWORD_MISMATCH = 'RESET_PASSWORD_MISMATCH'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR'

/* NOTIFICATION CENTER */
export const DISMISS_ERROR = 'DISMISS_ERROR'
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION'

/* COMMON ERROR */
export const UNEXPECTED_ERROR = 'UNEXPECTED_ERROR'

/* PROFILE */
export const PROFILE_NAME_UPDATED = 'PROFILE_NAME_UPDATED'
export const PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED'
export const PASSWORD_UPDATED = 'PASSWORD_UPDATED'
export const PASSWORD_UPDATE_FAILED = 'PASSWORD_UPDATE_FAILED'

/* ADDRESS */
export const ADDRESS_UPDATED = 'ADDRESS_UPDATED'
export const ADDRESS_UPDATE_FAILED = 'ADDRESS_UPDATE_FAILED'

/* INSTITUTE */
export const INSTITUTE_HANDLE_NAME = 'INSTITUTE_HANDLE_NAME'
export const INSTITUTE_CREATED = 'INSTITUTE_CREATED'
export const INSTITUTE_CREATION_FAILED = 'INSTITUTE_CREATION_FAILED'
